Create depletion functions
arfc/openmcyclus pull request #5
Opened 2023-01-31 21:53 UTC by abachma2

This PR adds a class to call the ``IndependentOperator`` class in Open MC to perform depletion and functions related to calling this class and converting the output compositions into a file format readable by Cyclus. This PR also adds a test suite for unit tests for these functions, as well as file needed to run the test suite. All tests pass on my local machine, I have an issue (#4) to get CI set up for tests. 

I expect that these functions will be updated/augmented once the coupling to the Cyclus archetype begins, but these functions provide a basis for what I believe will be needed. I am open to comments/suggestions on style and content.

2023-02-02 21:13 UTC, yardasol requested changes
Hi @abachma2, this looks fantastic! I have one big overall comments:
I'd highly recommend using [`pathlib`](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module) instead of OS, it's a more pythonic way of dealing with filesystems and in my experience is slightly less clunky. `pathlib` can't do _everything_ that `os` can, but for this use case it's more appropriate.

All my other comments and suggestions are below.

2023-02-02 21:13 UTC, yardasol commented on openmcyclus/depletion.py
> +        return model
This allows optional support for `tallies.xml`
```suggestion
        model_kwargs = {"geometry": (self.path / "geometry.xml"),
                        "materials": (self.path / "materials.xml"),
                        "settings": (self.path / "settings.xml")}
        tallies_path = self.path / "tallies.xml"
        if tallies_path.exists():
            model_kwargs["tallies"] = tallies_path
        model = openmc.Model.from_xml(**model_kwargs)
        return model
```

2023-02-02 21:13 UTC, yardasol commented on openmcyclus/depletion.py
> +        microxs = od.MicroXS.from_csv(str(self.path + "micro_xs.csv"))
```suggestion
        microxs = od.MicroXS.from_csv(self.path / "micro_xs.csv")
```

2023-02-02 21:13 UTC, yardasol commented on openmcyclus/depletion.py
> +        results = od.Results.from_hdf5(str(self.path + "depletion_results.h5"))
`Results.from_hdf5` is being depreciated. 
```suggestion
        results = od.Results(self.path / "depletion_results.h5")
```

2023-02-02 21:13 UTC, yardasol commented on tests/unit_tests/test_depletion.py
> +        assert obs
```suggestion
        assert isinstance(model, openmc.model.model.Model)
```

2023-02-02 21:13 UTC, yardasol commented on tests/unit_tests/test_depletion.py
> +        assert obs
```suggestion
        assert isinstance(microxs, pd.DataFrame)
```

2023-02-02 21:13 UTC, yardasol commented on tests/unit_tests/test_depletion.py
> +        assert obs
```suggestion
        assert (self.deplete.path / "depletion_results.h5").exists()
```

2023-02-02 21:13 UTC, yardasol commented on tests/unit_tests/test_depletion.py
> +        os.system("rm " + self.deplete.path + "depltion_results.h5")
```suggestion
       (self.deplete.path / "depltion_results.h5").unlink()
```

2023-02-02 21:13 UTC, yardasol commented on tests/unit_tests/test_depletion.py
> +import os
```suggestion
import pathlib
```

2023-02-02 21:17 UTC, abachma2 commented on openmcyclus/depletion.py
> +            "depletion_results.h5")
I looked for a way to do that within OpenMC. Guess I missed that one. Thanks!

2023-02-02 23:30 UTC, abachma2 commented on README.md
> +required microscopic cross sections (``.xml`` file)for the model. The cross
I mean the ``.csv`` file for the cross sections, like the ``micro_xs.csv`` file that I added to the repo. I am trying to reduce the number of things OpenMC has to do, and I feel like if we tried to use the ``openmc.deplete.MicroXS.from_model()`` method then that would calculate the cross sections each time you call the depletion solver, which I don't want to do. Please correct me if I am incorrect in my understanding.

2023-02-02 23:39 UTC, abachma2 commented on openmcyclus/depletion.py
> +            power output of the reactor, assumed in MWe.
This is a really interesting question. Cyclus assumes the power is in MWe. So I feel like there are a few ways we can handle this:
- Convert MWe to MWth in the archetype, assuming a constant conversion
- Convert MWe to MWth in a method in this class, assuming a constant conversion
- Convert MWe to MWth in the archetype with a user defined conversion 
- Convert MWe to MWth in a method in this class with a user defined conversion
Thoughts? I'm okay with moving this into an issue and discussing later if you feel this isn't vital to this PR.

2023-02-03 00:12 UTC, abachma2 commented on openmcyclus/depletion.py
> +            "depletion_results.h5")
I changed the code to what you suggested and when I run the tests I get ``TypeError: IndependentOperator.__init__() got an unexpected keyword argument 'output_dir'``. Any thoughts?

2023-02-03 16:45 UTC, yardasol commented on README.md
> +required microscopic cross sections (``.xml`` file)for the model. The cross
Gotcha. In that case you should just change the ``.xml`` to a ``.csv`` in the docstring.

You are correct, we do not want to call `openmc.deplete.MicroXS.from_model()` during runtime, that goes against the point of using `IndependentOperator`.

2023-02-03 16:47 UTC, yardasol commented on openmcyclus/depletion.py
> +            "depletion_results.h5")
My bad, `output_dir` is not a parameter for `IndependentOperator.__init__()`, it's an attribute that you'll need to set manually. So after creating `ind_op`, you should write
```python
ind_op.output_dir = self.path
```

2023-02-03 16:49 UTC, yardasol commented on openmcyclus/depletion.py
> +            power output of the reactor, assumed in MWe.
I think the fourth option would be easiest to do, and you can have a default conversion factor of 3, which will get you in the ballpark I think.

2023-02-03 18:57 UTC, abachma2 commented
I have made the remaining changes requested, and the tests all pass still.

2023-02-07 14:36 UTC, abachma2 commented
@yardasol bump

2023-02-07 18:33 UTC, yardasol approved these changes
Apologies for the long wait on this @abachma2. Great work on these changes. Just one quick change and then I'll merge

2023-02-07 18:33 UTC, yardasol commented on openmcyclus/depletion.py
> +        ~:class:`~openmc.deplete.IndependentOperator`
```suggestion
        :class:`~openmc.deplete.IndependentOperator`
```

2023-02-07 18:42 UTC, merged